# SPDX-FileCopyrightText: Copyright © 2026 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0

stages:
  - lint
  - build
  - maintenance

variables:
  GIT_DEPTH: "0"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  YARN_ENABLE_GLOBAL_CACHE: "false"
  YARN_CACHE_FOLDER: "$CI_PROJECT_DIR/.yarn/cache"

.build-rules: &build_rules
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
.gradle-cache: &gradle-cache
  cache:
    key:
      files:
        - gradle/wrapper/gradle-wrapper.properties
    paths:
      - .gradle/configuration-cache
      - .gradle/caches
      - .gradle/wrapper

license:
  stage: lint
  image: python:3-alpine
  timeout: 2m
  <<: *build_rules
  script:
    - pip install -r requirements.txt
    - reuse lint

format:
  stage: lint
  image: node:lts-alpine
  timeout: 2m
  <<: *build_rules
  cache:
    key:
      files:
        - package.json
        - yarn.lock
    paths:
      - .yarn/cache
      - .pnp.*js
      - .yarn/install-state.gz

  script:
    - corepack enable
    - yarn install --immutable --inline-builds --check-resolutions
    - yarn exec prettier --ignore-unknown --check "**"

format-kotlin:
  stage: lint
  image: eclipse-temurin:21-alpine
  timeout: 2m
  <<: *build_rules
  variables:
    KTLINT_VERSION: "1.8.0"
  cache:
    key: ktlint-${KTLINT_VERSION}
    paths:
      - scripts/.tools
  script:
    - ./scripts/ktlint.sh "*.gradle.kts" "**/*.gradle.kts"

build:
  stage: build
  image: eclipse-temurin:21-alpine
  timeout: 10m
  <<: *build_rules
  <<: *gradle-cache
  variables:
    GRADLE_ENCRYPTION_KEY: "$GRADLE_ENCRYPTION_KEY"
  script:
    - ./gradlew build --build-cache --console=plain

full:
  stage: build
  image: eclipse-temurin:21-alpine
  timeout: 10m
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  <<: *gradle-cache
  variables:
    GRADLE_ENCRYPTION_KEY: "$GRADLE_ENCRYPTION_KEY"
  script:
    - ./gradlew build --no-build-cache --no-configuration-cache --rerun-tasks --scan

renovate:
  stage: maintenance
  image: renovate/renovate:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  variables:
    RENOVATE_PLATFORM: gitlab
    RENOVATE_ENDPOINT: https://gitlab.com/api/v4
    RENOVATE_CONFIG_FILE: .github/renovate.json5
    RENOVATE_REPOSITORIES: $CI_PROJECT_PATH
  script:
    - renovate
