# SPDX-FileCopyrightText: Copyright © 2025, 2026 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0

version = 1

# file is mostly used for vendored and generated files as they are hard to maintain the license for

# yarn
[[annotations]]
path = "yarn.lock"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

# asdf
[[annotations]]
path = ".tool-versions"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

# maven
[[annotations]]
path = "mvnw*"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".mvn/wrapper/*"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "Apache-2.0"
