# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT

name: build
on: [push]
jobs:
  build:
    uses: xenoterracide/github/.github/workflows/maven.yml@eaaf2bd01cdd32b3950137c2f935787108cb46fe # develop
    permissions:
      actions: write
      contents: read
      packages: read
