# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT

name: build
on: [push]
jobs:
  build:
    uses: xenoterracide/github/.github/workflows/maven.yml@2f8a2c12bd3e8e98da4ad94e6262bce28d0407ba # develop
    permissions:
      actions: write
      contents: read
      packages: read
