# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT

name: build
on: [push]
jobs:
  build:
    uses: xenoterracide/github/.github/workflows/maven.yml@757aa909e8d0a45f65e8837f28a0c05ca99745e6 # develop
    permissions:
      actions: write
      contents: read
      packages: read
