# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT

name: devtools-regression
on: push
permissions:
  contents: read
jobs:
  regression-prettier:
    uses: xenoterracide/github/.github/workflows/regression-devtool-prettier.yml@1242ed6bc1748206a8d8ea35f7182e84890a986a # develop
  regression-lint-staged:
    uses: xenoterracide/github/.github/workflows/regression-devtool-lint-staged.yml@1242ed6bc1748206a8d8ea35f7182e84890a986a # develop
  regression-git-conventional-commits:
    uses: xenoterracide/github/.github/workflows/regression-devtool-git-conventional-commits.yml@1242ed6bc1748206a8d8ea35f7182e84890a986a # develop
  regression-reuse:
    uses: xenoterracide/github/.github/workflows/regression-devtool-reuse.yml@1242ed6bc1748206a8d8ea35f7182e84890a986a # develop
