# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT

name: pre-commit
on: push
permissions:
  contents: read
jobs:
  license:
    uses: xenoterracide/github/.github/workflows/license.yml@2eb2aed57a9a91fe6bdcb44491cefd7ae224bb24 # develop
  prettier:
    uses: xenoterracide/github/.github/workflows/prettier.yml@2eb2aed57a9a91fe6bdcb44491cefd7ae224bb24 # develop
